<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>true</ImplicitUsings>
        <TargetFramework>net48</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Configurations>Debug 2020;Debug 2021;Debug 2022;Debug 2023;Debug 2024;Release 2020;Release 2021;Release 2022;Release 2023;Release 2024</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Revit_All_Main_Versions_API_x64" IncludeAssets="build; compile" PrivateAssets="All" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.12.0" />
        <PackageReference Include="NUnit" Version="3.13.3" />
        <PackageReference Include="ricaun.RevitTest.TestAdapter" Version="1.2.0" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="source_files\" />
    </ItemGroup>
</Project>