<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>preview</LangVersion>
        <UseWpf>true</UseWpf>
        <Nullable>enable</Nullable>
        <Version>2.0.1</Version>
        <Title>Craftify.Geometry</Title>
        <Authors>Mariyan Slesar</Authors>
        <Description>Enhance your Revit development with advanced geometric operations, sophisticated BoundingBoxXYZ tools, and intuitive visualization capabilities.</Description>
        <PackageProjectUrl>https://github.com/MariyanDeveloper/Craftify.Geometry</PackageProjectUrl>
        <PackageIcon>Craftify.png</PackageIcon>
        <RepositoryUrl>https://github.com/MariyanDeveloper/Craftify.Geometry</RepositoryUrl>
        <PackageTags>RevitAPI, Geometry</PackageTags>
        <PackageId>Craftify.Geometry</PackageId>
    </PropertyGroup>
    
<!--    live-reload-->
<!--    <PropertyGroup Condition="'$(Configuration)'=='Debug'">-->
<!--        <IncludePackageReferencesDuringMarkupCompilation>false</IncludePackageReferencesDuringMarkupCompilation>-->
<!--        <Revision>$([MSBuild]::Divide($([System.DateTime]::Now.TimeOfDay.TotalSeconds), 4).ToString('F0'))</Revision>-->
<!--        <PackageAssemblyVersion>.Dev.$(Version).$(Revision)</PackageAssemblyVersion>-->
<!--    </PropertyGroup>-->
<!--    <PropertyGroup>-->
<!--        <AssemblyName>$(PackageId)$(PackageAssemblyVersion)</AssemblyName>-->
<!--    </PropertyGroup>-->
    
    <ItemGroup>
<!--      <PackageReference Include="Craftify.Shared" Version="1.0.0" />-->
        <PackageReference Include="Revit_All_Main_Versions_API_x64"
                          Version="2023.0.0"
                          IncludeAssets="build; compile"
                          PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup>
      <None Include="..\..\..\ProductInformation\Craftify.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>Craftify.png</Link>
      </None>
    </ItemGroup>
    <ItemGroup>
      <Reference Include="Craftify.Functional">
        <HintPath>..\..\..\Craftify.Functional\src\Craftify.Functional\bin\Debug\netstandard2.0\Craftify.Functional.dll</HintPath>
      </Reference>
      <Reference Include="Craftify.Shared">
        <HintPath>..\..\..\Craftify.Shared\src\Craftify.Shared\bin\Debug\net48\Craftify.Shared.dll</HintPath>
      </Reference>
    </ItemGroup>
    
</Project>
